### ISSUE TITLE
Upgrade Storybook from 6.0 to 6.1

### ISSUE THREAD

**Issue by uqmchu** [uq-its-ss/design-system#128]
I've tried upgrading to [~~6.1.1~~ 6.1.10](https://github.com/storybookjs/storybook/issues/11884), however, there are too many issues/bugs that still have not been reported and fixed.

Some issues observed (tick if observed fix):
- [x] ~~custom logo disappears~~
- [x] ~~`addon/backgrounds` is buggy esp. w/ `addon/docs`~~:
  - [x] ~~background colour doesn't change~~
  - [x] ~~sometimes the page content disappears when the background tool is clicked~~
  - [x] ~~grid feature no longer works~~
- [ ] code fenced sass/scss code is monochromatic (not a deal breaker as we can take of it via customisation)
- [ ] ~~`Canvas` elem with toolbar no longer displays button to open canvas in new tab if story is created within MDX doc~~ Not specific to this version (needs investigation).

Two positive notes are that search and navigation work much faster and [single story hoisting](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#single-story-hoisting) is good.

We need to revisit this upgrade in the next few releases. We might even need to consider reporting bugs to the Storybook working group ourselves.

**Comment by Bcrunk** [comment]
@uqmchu , just confirming that it is the storybook update that has issues, when those issues are fixed we will move forward with updating? 

Its not issues with our system that need to be fixed at this stage.

**Comment by uqmchu** [comment]
The upgrade seems good to go. The only thing is that the scss syntax in the code fences are coming through with black text only. Changing the code fence syntax declaration to `css` seems to fix it but this is not ideal. As we plan to customise the code example style anyway, this is not a big deal.
