### ISSUE TITLE
Equalised grid-menu should be achieved using CSS grid

### ISSUE THREAD

**Issue by uqmchu** [uq-its-ss/design-system#140]
This effect shouldn't require JS (fallback to flexbox if necessary).

**Comment by Bcrunk** [comment]
Agree, css has the tools to achieve these outcomes without the use of JS. 

Will create a story to review and resolve this issue.

**Comment by uqtgeor4** [comment]
Removed JS dependency. Grid menu item equalises height with CSS grid.
