### ISSUE TITLE
Deep nested elements should be avoided - ITSADSSD-29925

### ISSUE THREAD

**Issue by uq-aaron** [uq-its-ss/design-system#142]
When looking through the scss for the header component - https://github.com/uq-its-ss/design-system/blob/master/packages/header/src/scss/_component.scss

I noticed that there is some very deep nesting of selectors happening here. In some places 6 or 7 levels deep. The BEM naming methodology should resolve the need for the deep nesting.
The deep nested elements will also make it difficult for others to overwrite in the future, as well as increasing the selector length and in turn, increasing the size of the compiled css files.

The header component should be refactored to reduce the need of deep nested css selectors for styling.

**Comment by Bcrunk** [comment]
@uq-aaron thanks for the feedback, I will create a new story in our backlogs to review the nesting levels. 

We created the design, but the first implementation was done for the Future students website by an external agency. The Design system has adopted that code in the first iteration and I agree there are plenty of improvements to be made. 

The header is meant to highly modular so any deep nesting will need to be addressed. Appreciate the review and feedback, we are spread pretty thin at the moment so value any help we can get reviewing components for improvements.
