### ISSUE TITLE
Public repository

### ISSUE THREAD

**Issue by uq-aaron** [uq-its-ss/design-system#150]
Hi, it looks as though this repository is public.

Just wondering if that is intentional, if it is to be open to the public, or if it should be private to UQ only.

**Comment by Bcrunk** [comment]
Hey Aaron 

The decision was made to make it public. 

- Collaborate with UQ teams outside of ITS. 
- External contractors and marketing teams. 

Yes there is still a lot of discussion around licensing and who can use the repo etc etc. 

If you have any specific concerns let me know.
