### ISSUE TITLE
Core: needs are really good cleanup before it's release ready

### ISSUE THREAD

**Issue by uqmchu** [uq-its-ss/design-system#162]
- [x] Remove Fontawesome 4 dependency
- [x] Remove old UQ icons stuff
- [x] Remove variables and mixins that are package-specific and shouldn't be in core (most likely unused anyway)
- [x] Remove old background images

**Comment by Bcrunk** [comment]
Clean out these folders and references 

\packages\core\src\fonts\uq-icons
packages\core\src\images

**Comment by uqtgeor4** [comment]
Clean up done on the above stated.
