### ISSUE TITLE
Replace with corresponding variables - ITSADSSD-32678

### ISSUE THREAD

**Issue by uqtgeor4** [uq-its-ss/design-system#174]
- Replace rem/em/px to its corresponding variables where applicable.
- Consistency across components to use component specific variables assigned with core variables where possible in (packages/comp/src/scss/_global.scss) rather than use core variables directly in (packages/comp/src/scss/_component.scss).
- Replace random colours with its corresponding core variables where applicable (e.g. rgba(core.$uq-black, .3);)

**Comment by Bcrunk** [comment]
Work has been completed as part of Drupal / UQDS alignment work.
