### ISSUE TITLE
Inconsistent size naming of fonts

### ISSUE THREAD

**Issue by Bcrunk** [uq-its-ss/design-system#183]
There is inconsistency in how we name and structure size in "space" vs "fonts" 

- Make the naming format the same. convert l, m, s to lg, md, sm 
- Default space class has no size name, do the same with the default font size which is currently medium. 

This will improve consistency of usage through the system, opens up one more size naming option.

**Comment by uqtgeor4** [comment]
This is resolved and merged.
https://github.com/uq-its-ss/design-system/pull/192
