### ISSUE TITLE
Hero Component reliant on H1 tag

### ISSUE THREAD

**Issue by Bcrunk** [uq-its-ss/design-system#188]
While trailing the HERO banner I noticed that the HERO is currently coded with a H1 dependency

This means it is not modular and cannot be used with DIV or H2, it is also susceptible to other libraries modifying the style. 

Recommend having a title class that matches the BEM naming convention

**Comment by Bcrunk** [comment]
I also noted that original future students component keeps the content to only 50% of the layout, it does not allow it to expand the whole width.

**Comment by uqtgeor4** [comment]
On checking this looks to be resolved now
