### ISSUE TITLE
Kitchen Sink Pane styles broken

### ISSUE THREAD

**Issue by Bcrunk** [uq-its-ss/design-system#189]
Kitchen sink pane styles are broken. 

The pane classes have been updated with the uq prefix. The kitchen sink classes are missing the prefix. 
https://design-system.uq.edu.au/?path=/story/gallery-examples-kitchen-sink--kitchen-sink

**Comment by uqtgeor4** [comment]
Fixed. Prefixes added to the kitchen sink pane example.
