### ISSUE TITLE
Header tags have incorrect padding and margin applied - ITSADSSD-31812

### ISSUE THREAD

**Issue by Bcrunk** [uq-its-ss/design-system#197]
Header tags have the incorrect padding and margin applied, this is causing spacing issues on components.

**Comment by Bcrunk** [comment]
Options
- FIx the bug
- Drop the options
- uplift component 

Need to choose one of these and add as a story.

**Comment by uqtgeor4** [comment]
Margin top & Margin bottom changed for H1 - H6 Header Tags.
Visually looking fine now. Need thorough check within all components though
