### ISSUE TITLE
Additional styles and consistent messaging - ITSADSSD-33926 and ITSADSSD-33934

### ISSUE THREAD

**Issue by uq-aaron** [uq-its-ss/design-system#234]
**Bug perhaps:**
The symbols utilised for the page based alerts
https://design-system.uq.edu.au/?path=/docs/components-alert--alert-warning

Do not match the symbols for the form alerts and errors
https://design-system.uq.edu.au/?path=/docs/components-form-controls--input-text-error

This provides an inconsistent experience for the user where the iconography could be important, especially for colour blind accessibility.

**Feature request:**
Although usage would be infrequent, I would also like to see the Info and Warning styling implemented on the form controls where feedback can be provided that does not necessarily indicate a success or error

**Comment by Bcrunk** [comment]
I will add a story to review and update, the forms were created early on and looks like they might not be referencing the icon library but using custom icons.
