### ISSUE TITLE
Site Title: Example 2: Search feature is not clickable

### ISSUE THREAD

**Issue by Bcrunk** [uq-its-ss/design-system#93]
**Describe the bug**
Site title: Example 2: with site header - the search icon should be clickable and show the search box. it does not function 

**To Reproduce**
1. click the search icon top right

**Expected behavior**
SHould have expanded to show search options

**Screenshots**
![image](https://user-images.githubusercontent.com/8379323/93940678-47bdb180-fd70-11ea-878f-9b07d31cd605.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Firefox

**Comment by uqmchu** [comment]
No longer required.
